import { Trick } from "./types";

export const STAGES = [
  { number: 1, name: "Foundation", description: "The stuff you actually need before any trick. Nobody skips this without paying for it later." },
  { number: 2, name: "Flat Ground Basics", description: "Your first real tricks. The ollie changes everything — it's the gateway drug of skateboarding." },
  { number: 3, name: "Flat Ground Intermediate", description: "Now we're cooking. Flips, 180s, and nose manuals. This is where it starts to feel like actual skateboarding." },
  { number: 4, name: "Transition Intro", description: "Time to skate some ramps. Dropping in is terrifying the first time. That's normal. You'll survive." },
  { number: 5, name: "Street Basics", description: "Curbs, ledges, small gaps. The street is your playground now." },
];

export const TRICKS: Trick[] = [
  // === STAGE 1: Foundation ===
  {
    id: "stance",
    name: "Finding Your Stance",
    stage: 1,
    description: "Regular or goofy? Push with your back foot, front foot near the bolts. There's no wrong answer — your body knows. Try both and see which feels less like you're about to die.",
    difficulty: 1,
    prerequisites: [],
    injuryRisk: "low",
    searchQuery: "how to find skateboard stance regular vs goofy adult beginner",
    tips: [
      "Have someone gently push you from behind — whichever foot you step forward with is probably your front foot",
      "Regular = left foot forward. Goofy = right foot forward. Neither is better.",
      "If both feel weird, you're normal. Pick one and commit for at least a week.",
    ],
  },
  {
    id: "pushing",
    name: "Pushing",
    stage: 1,
    description: "The most fundamental skill. Front foot on the board pointing forward, back foot pushes along the ground. Keep your weight centered over the board, not leaning back like you're afraid of it (even though you are).",
    difficulty: 2,
    prerequisites: ["stance"],
    injuryRisk: "low",
    searchQuery: "how to push on a skateboard for beginners adults step by step",
    tips: [
      "Point your front foot toward the nose while pushing, then angle it sideways once both feet are on",
      "Push with long, smooth strokes — not little frantic taps",
      "Practice in a parking lot with smooth ground, not on sidewalk cracks",
      "Bend your front knee slightly — stiff legs are how you eat pavement",
    ],
  },
  {
    id: "stopping",
    name: "Stopping",
    stage: 1,
    description: "Three ways to stop: foot brake (drag your back foot), power slide (advanced, skip for now), or the bail-and-run (step off and let the board go). Master the foot brake first — it's the most controlled and least dramatic.",
    difficulty: 2,
    prerequisites: ["pushing"],
    injuryRisk: "low",
    searchQuery: "how to stop on a skateboard foot brake beginner adult",
    tips: [
      "Shift your weight to your front foot before dragging your back foot",
      "The sole of your shoe does the braking, not the toe — flat foot drag",
      "Practice at slow speeds first. Seriously. Slow speeds.",
      "Don't use your tail to brake — it destroys your board and looks bad",
    ],
  },
  {
    id: "turning",
    name: "Turning & Carving",
    stage: 1,
    description: "Lean to turn. Toe-side leans take you one way, heel-side the other. Loose trucks turn more but feel wobblier. Start with medium-tight trucks and loosen as you get comfortable. Carving is just turning back and forth — it builds balance and feels amazing.",
    difficulty: 3,
    prerequisites: ["pushing"],
    injuryRisk: "low",
    searchQuery: "how to turn and carve on skateboard beginner adult tutorial",
    tips: [
      "Your shoulders lead the turn — look where you want to go",
      "Toe-side turns feel more natural for most people. Heel-side takes practice.",
      "Practice big, sweeping turns in an empty parking lot before tight turns",
      "If your trucks feel too tight or loose, adjust the kingpin nut a quarter turn at a time",
    ],
  },
  {
    id: "falling",
    name: "Falling Safely",
    stage: 1,
    description: "You WILL fall. The difference between a funny story and an ER visit is knowing how. Roll with it — literally. Tuck your arms, roll onto your shoulder, slide it out. Never catch yourself with straight arms (hello, broken wrist). Wear pads. You're an adult with a job and responsibilities.",
    difficulty: 2,
    prerequisites: [],
    injuryRisk: "low",
    searchQuery: "how to fall safely skateboarding adult beginner avoid injury",
    tips: [
      "Wrist guards are the single best protective investment. Wear them.",
      "Practice falling on grass first — seriously, just practice the roll",
      "Knee pads let you slide on your knees instead of tumbling. Game changer on ramps.",
      "When you feel yourself going down, bend your knees and try to roll, don't brace",
      "If you're over 30, nobody will judge you for wearing pads. They'll judge you for the cast.",
    ],
  },
  {
    id: "riding-comfort",
    name: "Comfortable Cruising",
    stage: 1,
    description: "Before you learn any tricks, you need to be able to just... ride. Push around for 20-30 minutes without thinking about balance. Go over small cracks. Step off and back on. This is boring but it's the foundation everything else is built on.",
    difficulty: 3,
    prerequisites: ["pushing", "stopping", "turning"],
    injuryRisk: "low",
    searchQuery: "skateboard cruising practice beginner comfortable riding tips",
    tips: [
      "Set a goal: ride for 30 minutes without stepping off (except to push)",
      "Practice riding over small cracks and bumps — lift your front wheels slightly",
      "Try riding in both directions, even your weak side",
      "Ride with music. It makes practice feel like fun instead of homework.",
    ],
  },
  {
    id: "tick-tack",
    name: "Tick-Tacks",
    stage: 1,
    description: "Shift weight to your tail, lift the front wheels, and pivot left-right to generate momentum. It's goofy-looking but builds essential tail balance and is genuinely useful for navigating tight spaces. Plus it's your first taste of controlling the board beyond just riding it.",
    difficulty: 3,
    prerequisites: ["riding-comfort"],
    injuryRisk: "low",
    searchQuery: "how to tic tac skateboard beginner tutorial step by step",
    tips: [
      "Light pressure on the tail — you only need the front wheels an inch off the ground",
      "Use your hips and shoulders to initiate the pivot, not just your feet",
      "Try to tic-tac uphill slightly — great balance builder",
    ],
  },

  // === STAGE 2: Flat Ground Basics ===
  {
    id: "ollie",
    name: "Ollie",
    stage: 2,
    description: "The ollie is THE fundamental trick. Pop the tail, slide your front foot up, level out in the air. It will take weeks to months to learn. That's normal. Every pro sucked at ollies for a long time. The sliding motion of the front foot is the hardest part — it needs to become muscle memory.",
    difficulty: 5,
    prerequisites: ["riding-comfort", "tick-tack"],
    injuryRisk: "medium",
    searchQuery: "how to ollie skateboard step by step beginner adult tutorial",
    tips: [
      "Practice stationary first — in grass or on carpet to remove the rolling fear",
      "The pop comes from snapping your ankle, not stomping your whole leg",
      "Your front foot SLIDES up the board — it's not a jump, it's a drag",
      "Film yourself from the side. You're probably not sliding your front foot enough.",
      "Commit to doing 50 ollie attempts per session. Repetition is the only teacher.",
    ],
  },
  {
    id: "manual",
    name: "Manual",
    stage: 2,
    description: "Ride on your back two wheels. It's a balance trick — shift your weight over the back trucks without popping the tail to the ground. Think of it like a wheelie. Start with 5-foot manuals and work your way up. Great for building board control.",
    difficulty: 4,
    prerequisites: ["riding-comfort"],
    injuryRisk: "low",
    searchQuery: "how to manual skateboard beginner tutorial balance tips",
    tips: [
      "Arms out for balance. You'll look silly. It works.",
      "Find the balance point — it's further back than you think",
      "Set distance goals: manual from one crack to the next",
      "Keep your knees bent and your weight centered, not leaning back",
    ],
  },
  {
    id: "fakie-riding",
    name: "Fakie Riding",
    stage: 2,
    description: "Riding backward — same stance, opposite direction. You're rolling with your nose as the back of the board. It feels weird at first because your weight distribution is flipped. Essential for learning fakie tricks later and just generally being comfortable on your board.",
    difficulty: 4,
    prerequisites: ["riding-comfort"],
    injuryRisk: "low",
    searchQuery: "how to ride fakie skateboard beginner tutorial switch riding",
    tips: [
      "Start by rolling forward, then let yourself roll backward on a slight incline",
      "Your weight should be slightly over the 'back' trucks (which are now in front)",
      "Practice pushing fakie — it feels awkward but builds great board sense",
      "Don't look at your feet. Look where you're going. Trust the board.",
    ],
  },
  {
    id: "pivot",
    name: "Frontside & Backside Pivot",
    stage: 2,
    description: "A 180-degree turn on your back wheels. Frontside means your chest faces the direction of rotation, backside means your back does. It's basically an advanced tic-tac. Pivots are building blocks for reverts and 180s later.",
    difficulty: 4,
    prerequisites: ["tick-tack", "riding-comfort"],
    injuryRisk: "low",
    searchQuery: "how to frontside backside pivot skateboard beginner tutorial",
    tips: [
      "Wind up your shoulders before the pivot — they lead the rotation",
      "Keep the front wheels just barely off the ground",
      "Frontside is usually easier to learn first",
      "Practice both directions even if one feels terrible. Balance is everything.",
    ],
  },
  {
    id: "rolling-ollie",
    name: "Rolling Ollie",
    stage: 2,
    description: "Once your stationary ollie is solid, it's time to ollie while moving. This is where the fear kicks in because now gravity and momentum are both involved. Start slow — walking speed — and gradually build up. The technique is the same, your brain just needs to trust it while rolling.",
    difficulty: 6,
    prerequisites: ["ollie"],
    injuryRisk: "medium",
    searchQuery: "how to ollie while rolling moving skateboard beginner tips",
    tips: [
      "Start at walking speed. Literally walking speed.",
      "The motion is the same as stationary — don't overthink it",
      "Lean slightly forward. Most people lean back out of fear and the board shoots out.",
      "Set a small object to ollie over once you're consistent — a stick, a pencil",
    ],
  },
  {
    id: "shuvit",
    name: "Pop Shove-It",
    stage: 2,
    description: "The board rotates 180 degrees under you while you stay facing forward. Scoop the tail backward with your back foot. It's one of the first tricks that makes you feel like an actual skateboarder. Easier than a kickflip, almost as satisfying.",
    difficulty: 5,
    prerequisites: ["ollie"],
    injuryRisk: "medium",
    searchQuery: "how to pop shove it skateboard beginner tutorial step by step adult",
    tips: [
      "The scoop is more of a flick backward with your toes, not a full kick",
      "Your front foot barely does anything — just lift it and let the board spin under you",
      "Keep your shoulders level and parallel to the board",
      "Commit to landing on it. Half-committing is how you get shinners.",
    ],
  },

  // === STAGE 3: Flat Ground Intermediate ===
  {
    id: "kickflip",
    name: "Kickflip",
    stage: 3,
    description: "The iconic trick. Ollie, then flick your front foot off the heel edge of the nose to make the board flip. It will take hundreds of attempts. The flick is a subtle ankle motion — you're not kicking the board, you're sliding and flicking off the edge.",
    difficulty: 7,
    prerequisites: ["rolling-ollie"],
    injuryRisk: "medium",
    searchQuery: "how to kickflip skateboard beginner tutorial step by step adult",
    tips: [
      "Front foot angled slightly with toes hanging off the toe-side edge",
      "The flick goes off the corner of the nose — up AND out",
      "Practice the flick motion while sitting down to build muscle memory",
      "Landing with just your back foot first is normal. Work on catching it with both.",
      "This trick has a notorious learning curve. 2-3 months of focused practice is normal.",
    ],
  },
  {
    id: "heelflip",
    name: "Heelflip",
    stage: 3,
    description: "Like a kickflip but the board flips the opposite way because you're flicking with your heel off the toe side. Some people find heelflips more natural than kickflips. Try both and see which clicks — there's no rule that says kickflip has to come first.",
    difficulty: 7,
    prerequisites: ["rolling-ollie"],
    injuryRisk: "medium",
    searchQuery: "how to heelflip skateboard beginner tutorial step by step",
    tips: [
      "Front foot with heel hanging off the toe-side edge",
      "The flick is more of a forward kick off the nose corner",
      "Keep your shoulders square to the board — twisting is the most common mistake",
      "Some find heelflips easier than kickflips. If kickflips aren't clicking, try this.",
    ],
  },
  {
    id: "fs-180",
    name: "Frontside 180",
    stage: 3,
    description: "An ollie with a 180-degree frontside rotation. Your chest opens up toward the direction of travel. Wind up your shoulders before you pop. This is your gateway to landing fakie and eventually doing bigger rotations.",
    difficulty: 6,
    prerequisites: ["rolling-ollie", "pivot"],
    injuryRisk: "medium",
    searchQuery: "how to frontside 180 ollie skateboard beginner tutorial",
    tips: [
      "Wind up your shoulders BEFORE you pop — the rotation starts from the top down",
      "Your head and shoulders should be at 90 degrees before your feet leave the ground",
      "Commit to the full 180. Landing at 90 and pivoting the rest is fine at first.",
      "You'll land fakie — make sure you're comfortable riding fakie first",
    ],
  },
  {
    id: "bs-180",
    name: "Backside 180",
    stage: 3,
    description: "Same idea, opposite rotation — your back faces the direction of travel mid-rotation. Many people find this harder because you're essentially blind during the rotation. The trick is to lead with your head and look over your shoulder.",
    difficulty: 7,
    prerequisites: ["rolling-ollie", "pivot"],
    injuryRisk: "medium",
    searchQuery: "how to backside 180 ollie skateboard beginner tutorial",
    tips: [
      "Look over your back shoulder to initiate the rotation",
      "This one requires more commitment than frontside — you can't see where you're going mid-trick",
      "The scoop of the tail helps with the rotation",
      "Practice backside pivots extensively before attempting this",
    ],
  },
  {
    id: "nose-manual",
    name: "Nose Manual",
    stage: 3,
    description: "Manual on the front two wheels. Shift your weight forward over the nose without letting it touch the ground. Harder than a regular manual because bailing forward is scarier than bailing backward. Build up slowly.",
    difficulty: 6,
    prerequisites: ["manual"],
    injuryRisk: "medium",
    searchQuery: "how to nose manual skateboard beginner tutorial balance",
    tips: [
      "Start with very short nose manuals — just a second or two",
      "Your weight needs to be over the front bolts, not the very tip of the nose",
      "Arms out for balance. Always arms out.",
      "If you feel yourself going over the front, step off to the side — don't try to save it",
    ],
  },

  // === STAGE 4: Transition Intro ===
  {
    id: "dropping-in",
    name: "Dropping In",
    stage: 4,
    description: "Standing at the top of a ramp, tail on the coping, and committing your weight forward to roll down the transition. This is 95% mental. Your body will scream at you not to lean forward into a ramp. You have to override that instinct. Start on the smallest ramp you can find.",
    difficulty: 6,
    prerequisites: ["riding-comfort", "falling"],
    injuryRisk: "high",
    searchQuery: "how to drop in skateboard mini ramp beginner adult tutorial",
    tips: [
      "START SMALL. Find a 2-3 foot mini ramp, not a 6 foot halfpipe",
      "Stomp your front foot down and lean forward. Hesitation = falling backward.",
      "Wear knee pads. If you bail, slide on your knees. This is why knee pads exist.",
      "Have a friend hold your hand the first few times — no shame in that",
      "The commitment lean is the whole trick. Once you lean in, gravity does the rest.",
    ],
  },
  {
    id: "pumping",
    name: "Pumping",
    stage: 4,
    description: "Generating speed on transition without pushing. Compress your body going down, extend going up. Like pumping a swing. This is the key to flowing on ramps and the foundation of all transition skating.",
    difficulty: 5,
    prerequisites: ["dropping-in"],
    injuryRisk: "medium",
    searchQuery: "how to pump on mini ramp skateboard beginner tutorial",
    tips: [
      "Think of it like a squat: compress at the bottom of the transition, extend at the top",
      "Your arms help — pump them like you're doing a standing jump",
      "Start on a small quarter pipe, going back and forth",
      "The rhythm clicks suddenly — one session it'll just make sense",
    ],
  },
  {
    id: "kick-turn",
    name: "Kick Turn on Transition",
    stage: 4,
    description: "At the top of the ramp, pivot 180 on your back wheels to go back down. It's a tic-tac on a ramp. The height you go up determines how scary it is. Start barely above the flat bottom and work your way up.",
    difficulty: 6,
    prerequisites: ["pumping", "tick-tack"],
    injuryRisk: "medium",
    searchQuery: "how to kick turn on ramp mini ramp skateboard beginner",
    tips: [
      "Start low on the transition — you don't need to go to the coping",
      "Shoulders lead the turn, always. Look where you want to go.",
      "Backside kick turns (facing the ramp) are easier to start with",
      "Keep your weight slightly forward — leaning back on transition means sliding out",
    ],
  },
  {
    id: "rock-to-fakie",
    name: "Rock to Fakie",
    stage: 4,
    description: "Roll up the transition, let your front wheels go over the coping, then rock back and roll down fakie. Your first coping trick. It teaches you to interact with the lip of the ramp without fully committing to going over it.",
    difficulty: 7,
    prerequisites: ["kick-turn", "fakie-riding"],
    injuryRisk: "high",
    searchQuery: "how to rock to fakie mini ramp skateboard beginner tutorial",
    tips: [
      "The key moment is when your front wheels are over the coping — shift weight back to rock the board",
      "Don't lean too far forward or your wheels will catch the coping on the way back",
      "Lift your front wheels slightly as you come back over the coping",
      "Commit to rolling away fakie. Hesitation here leads to hanging up on the coping.",
    ],
  },

  // === STAGE 5: Street Basics ===
  {
    id: "ollie-up-curb",
    name: "Ollie Up a Curb",
    stage: 5,
    description: "Your first real street obstacle. Ride parallel to a curb and ollie up onto it. This is where your rolling ollie becomes functional. Start with low curbs — parking blocks are perfect practice.",
    difficulty: 6,
    prerequisites: ["rolling-ollie"],
    injuryRisk: "medium",
    searchQuery: "how to ollie up curb skateboard beginner street tutorial",
    tips: [
      "Approach parallel to the curb at a slight angle",
      "You need more speed than you think — momentum helps clear the height",
      "Pop the ollie slightly before the curb, not right at it",
      "Start with parking blocks or low ledges before real curbs",
    ],
  },
  {
    id: "50-50-grind",
    name: "50-50 Grind",
    stage: 5,
    description: "Ollie onto a ledge or curb and grind along it with both trucks. The most fundamental grind. Wax helps. A lot. Find a low, waxed curb and make it your best friend for a few weeks.",
    difficulty: 7,
    prerequisites: ["ollie-up-curb"],
    injuryRisk: "high",
    searchQuery: "how to 50-50 grind skateboard curb ledge beginner tutorial",
    tips: [
      "WAX THE LEDGE. Seriously. Skate wax or even a candle works.",
      "Approach at a slight angle, ollie on, and keep your weight centered",
      "Lean slightly toward the ledge — leaning away makes you slip off the back side",
      "Start with very short grinds. Even 6 inches counts.",
      "Come off the end by gently lifting your front wheels or doing a small ollie off",
    ],
  },
  {
    id: "boardslide",
    name: "Boardslide",
    stage: 5,
    description: "Ollie 90 degrees onto a rail or ledge so the middle of your board slides along it. Looks sick, feels scary, but on a low waxed ledge it's very doable. The ollie and 90-degree turn happen simultaneously.",
    difficulty: 8,
    prerequisites: ["ollie-up-curb", "fs-180"],
    injuryRisk: "high",
    searchQuery: "how to boardslide skateboard rail ledge beginner tutorial",
    tips: [
      "Start on a low, round rail or very well-waxed ledge",
      "Approach at a moderate angle — too perpendicular and you'll stick",
      "Turn your shoulders 90 degrees as you ollie — your board follows your upper body",
      "Look at the end of the rail/ledge, not at your feet",
      "Lean slightly forward over the obstacle. Leaning back = credit card. Don't Google that.",
    ],
  },
  {
    id: "small-gap",
    name: "Ollie Over a Gap",
    stage: 5,
    description: "Ollie over a sidewalk crack, a small gap between surfaces, or a set of cones. This is where your ollie becomes a tool for navigating terrain. Start embarrassingly small and work up.",
    difficulty: 6,
    prerequisites: ["rolling-ollie"],
    injuryRisk: "medium",
    searchQuery: "how to ollie over gap skateboard beginner tutorial distance",
    tips: [
      "Start with a line on the ground and ollie over it. Then a stick. Then a deck.",
      "Speed is your friend — more speed = more distance with the same pop",
      "Pop slightly before the gap, not at the edge",
      "Commit to landing on the bolts. Feet on the bolts = stability.",
    ],
  },
  {
    id: "manual-pad",
    name: "Manual Pad Tricks",
    stage: 5,
    description: "Ollie up onto a manual pad (raised flat surface), manual across it, and ollie off. Combines everything you've learned. This is real street skating — reading terrain and linking tricks together.",
    difficulty: 7,
    prerequisites: ["manual", "ollie-up-curb"],
    injuryRisk: "medium",
    searchQuery: "how to manual pad skateboard tricks beginner street tutorial",
    tips: [
      "Find a smooth, low manual pad — many skateparks have these",
      "Ollie up, immediately shift to manual, ride it out, then ollie or roll off the end",
      "Start with short manual pads and work your way to longer ones",
      "The transition from ollie to manual is the hard part — practice that shift",
    ],
  },
];

export function getTricksByStage(stage: number): Trick[] {
  return TRICKS.filter((t) => t.stage === stage);
}

export function getTrickById(id: string): Trick | undefined {
  return TRICKS.find((t) => t.id === id);
}

export function getPrerequisiteTricks(trick: Trick): Trick[] {
  return trick.prerequisites
    .map((id) => getTrickById(id))
    .filter((t): t is Trick => t !== undefined);
}

export function isTrickUnlockable(
  trickId: string,
  progress: Record<string, { status: string }>
): boolean {
  const trick = getTrickById(trickId);
  if (!trick) return false;
  if (trick.prerequisites.length === 0) return true;
  return trick.prerequisites.every(
    (preId) => progress[preId]?.status === "landed"
  );
}
